import "@/app/ui/styles/global.sass";
import Header from "@/app/ui/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <Header/>
        {
          children
        }
      </body>
    </html>
  );
}
